# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        JDKVersion: ["8","11","13","15"]


    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.JDKVersion }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.JDKVersion }}
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Install Gradle wrapper
      run: ./gradlew wrapper
      
    - name: Build with Gradle
      run: ./gradlew distZip

    - name: Test with Gradle
      run: ./gradlew test
      
    - name: Upload Artifact
      if: ${{ matrix.JDKVersion == '15' }}
      uses: actions/upload-artifact@v2.2.4
      with:
        path: build/distributions/*.zip
